### ISSUE TITLE
Module Foundation.core.animation is not avaiblable

### ISSUE THREAD

**Issue by adimux** [RelutionDev/foundationUltra#1]
I cloned your project on my /var/www/html folder and from the browser i get the error "foundation.core.animation is not available"

http://errors.angularjs.org/1.3.20/$injector/nomod?p0=foundation.core.animation

**Comment by JayDemitri** [comment]
Updated the gruntfile to include copying of foundation.core.animation.js then added to the head of the index.html page.

Please pull down the latest update and run 'grunt' again and all should be fine :)
